baseURL = "https://junki555.github.io/"
languageCode = "ja-jp"
weight = 1
title = "YoloEngg"
publishDir = "public"
theme = "hyde-hyde"
hasCJKLanguage = true
paginate = 10
paginatePath = "page"

[author]
	name = "junki555"

[params]
	layoutReverse = true

[params.social]
  	twitter = "JUNKI555"
  	github = "JUNKI555"
